"""참고문헌 내보내기 — BibTeX · RIS (2026-10-08, docs/quality.md C5, ADR-12).

- LLM·네트워크 없음. `brief.json`·`papers.json` 만으로 만든다 (`agent render` 와 같은 원칙).
- 번호와 순서는 report.md 의 참고문헌과 같다: `render_markdown` 에 빈 `_Refs` 를 넘겨 번호 매김을 그대로 받는다.
  관련성 ≤ 1 로 버려진 문헌은 리포트에 번호가 없으므로 여기서도 빠진다.
- Zotero·EndNote 는 RIS 가져오기, LaTeX 는 BibTeX. 키는 `<첫저자성><연도><제목첫단어>` (ASCII, 중복 시 a/b/c 접미).
"""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path
from typing import Any

from .report import _Refs, render_markdown
from .schemas import Paper, ResearchBrief

FORMATS = ("bibtex", "ris")


def reference_order(brief: ResearchBrief, papers: dict[str, Paper]) -> list[str]:
    """리포트 참고문헌 순서의 문헌 id 목록."""
    refs = _Refs()
    render_markdown(brief, papers, refs=refs)
    return list(refs.order)


def _ascii(s: str) -> str:
    return unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()


def _surname(author: str) -> str:
    """'Jane Q. Doe' → 'Doe', 'Doe, Jane' → 'Doe', 한글 이름은 그대로 (ASCII 화하면 비어 키에 못 쓴다)."""
    a = author.strip()
    if "," in a:
        a = a.split(",")[0]
    else:
        a = a.split()[-1] if a.split() else a
    return re.sub(r"[^A-Za-z0-9]", "", _ascii(a)) or "anon"


def _first_word(title: str) -> str:
    words = [w for w in re.findall(r"[A-Za-z][A-Za-z0-9]*", _ascii(title)) if len(w) > 3]
    return (words[0] if words else "paper").lower()


def bib_keys(ids: list[str], papers: dict[str, Paper]) -> dict[str, str]:
    """id → BibTeX 키. 같은 키가 생기면 a, b, c … 를 붙인다 (리포트 순서 기준)."""
    out: dict[str, str] = {}
    seen: dict[str, int] = {}
    for pid in ids:
        p = papers.get(pid)
        who = _surname(p.authors[0]) if p and p.authors else "anon"
        year = str(p.year) if p and p.year else "nd"
        base = f"{who}{year}{_first_word(p.title) if p else 'paper'}"
        n = seen.get(base, 0)
        seen[base] = n + 1
        out[pid] = base if n == 0 else f"{base}{chr(ord('a') + n - 1)}" if n <= 26 else f"{base}{n}"
    return out


def _bib_escape(s: str) -> str:
    return s.replace("{", "\\{").replace("}", "\\}").replace("&", "\\&").replace("%", "\\%")


def to_bibtex(brief: ResearchBrief, papers: dict[str, Paper]) -> str:
    ids = reference_order(brief, papers)
    keys = bib_keys(ids, papers)
    out = [f"% {len(ids)} references, numbered as in report.md ([n]). Generated by research-agent export.", ""]
    for n, pid in enumerate(ids, 1):
        p = papers.get(pid)
        if p is None:
            out += [f"@misc{{{keys[pid]},", f"  note = {{[{n}] {pid} (metadata unavailable)}}", "}", ""]
            continue
        kind = "article" if p.venue and not pid.startswith("arxiv:") else "misc"
        fields = [("title", _bib_escape(p.title))]
        if p.authors:
            fields.append(("author", " and ".join(_bib_escape(a) for a in p.authors)))
        if p.year:
            fields.append(("year", str(p.year)))
        if p.venue:
            fields.append(("journal" if kind == "article" else "howpublished", _bib_escape(p.venue)))
        if p.doi:
            fields.append(("doi", p.doi))
            fields.append(("url", f"https://doi.org/{p.doi}"))
        elif p.arxiv_id:
            fields.append(("eprint", p.arxiv_id))
            fields.append(("archiveprefix", "arXiv"))
            fields.append(("url", f"https://arxiv.org/abs/{p.arxiv_id}"))
        elif p.url:
            fields.append(("url", p.url))
        fields.append(("note", f"[{n}] in report.md"))
        body = ",\n".join(f"  {k} = {{{v}}}" for k, v in fields)
        out += [f"@{kind}{{{keys[pid]},", body, "}", ""]
    return "\n".join(out)


def to_ris(brief: ResearchBrief, papers: dict[str, Paper]) -> str:
    ids = reference_order(brief, papers)
    out: list[str] = []
    for n, pid in enumerate(ids, 1):
        p = papers.get(pid)
        if p is None:
            out += ["TY  - GEN", f"ID  - {pid}", f"N1  - [{n}] metadata unavailable", "ER  - ", ""]
            continue
        out.append("TY  - JOUR" if p.venue and not pid.startswith("arxiv:") else "TY  - GEN")
        out.append(f"ID  - {pid}")
        for a in p.authors:
            out.append(f"AU  - {a}")
        out.append(f"TI  - {p.title}")
        if p.year:
            out.append(f"PY  - {p.year}")
        if p.venue:
            out.append(f"JO  - {p.venue}")
        if p.doi:
            out.append(f"DO  - {p.doi}")
            out.append(f"UR  - https://doi.org/{p.doi}")
        elif p.arxiv_id:
            out.append(f"UR  - https://arxiv.org/abs/{p.arxiv_id}")
        elif p.url:
            out.append(f"UR  - {p.url}")
        if p.abstract:
            out.append(f"AB  - {' '.join(p.abstract.split())[:2000]}")
        out.append(f"N1  - [{n}] in report.md")
        out += ["ER  - ", ""]
    return "\n".join(out)


def export_run(run_dir: Path, fmt: str) -> dict[str, Any]:
    """실행 폴더의 brief.json·papers.json → references.bib / references.ris. 반환: 경로·편수."""
    if fmt not in FORMATS:
        raise ValueError(f"unknown format {fmt!r}; choose from {FORMATS}")
    d = Path(run_dir)
    brief_f, papers_f = d / "brief.json", d / "papers.json"
    if not brief_f.exists() or not papers_f.exists():
        raise ValueError(f"{d.name}: brief.json / papers.json 없음 (완주한 실행만 내보낸다)")
    brief = ResearchBrief.model_validate_json(brief_f.read_text(encoding="utf-8"))
    papers = {k: Paper.model_validate(v) for k, v in json.loads(papers_f.read_text(encoding="utf-8")).items()}
    text = to_bibtex(brief, papers) if fmt == "bibtex" else to_ris(brief, papers)
    out = d / ("references.bib" if fmt == "bibtex" else "references.ris")
    out.write_text(text, encoding="utf-8")
    return {"path": str(out), "refs": len(reference_order(brief, papers)), "bytes": len(text.encode("utf-8"))}
